#
# https://stackoverflow.com/questions/41509608/how-do-i-deploy-nuget-packages-in-travis-ci
#

language: csharp
solution: OkonkwoOandaV20.sln
install:
  - nuget restore ./OkonkwoOandaV20/OkonkwoOandaV20.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - xbuild ./OkonkwoOandaV20/OkonkwoOandaV20.sln /p:TargetFrameworkVersion="v4.5.2" /p:Configuration=Release
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./OkonkwoOandaV20/OkonkwoOandaV20Tests/bin/Release/OkonkwoOandaV20Tests.dll
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./nugetDeploy.sh && ./nugetDeploy.sh c75adb0c-6a34-42d7-a023-52ac94e269a5 https://www.nuget.org/api/v2/package
  on:
    branch: master